### ISSUE TITLE
Default export is not a function in 0.4.0

### ISSUE THREAD

**Issue by wopian** [vbenjs/vite-plugin-compression#11]
Upgrading from 0.3.6 to 0.4.0 results in a build error that the default export is not a function.

Vite config:
```js
import { defineConfig } from 'vite' // 2.7.10
import compression from 'vite-plugin-compression'

export default defineConfig({
  plugins: [
    ...,
    compression()
  ]
})
```

Build log:

```sh
$ vite build
failed to load config from /home/runner/work/.../vite.config.js
error during build:
TypeError: compression is not a function
    at file:///home/runner/work/.../vite.config.js?t=1641808119900:51:5
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async loadConfigFromFile (/home/runner/work/.../node_modules/vite/dist/node/chunks/dep-76613303.js:75061:31)
    at async resolveConfig (/home/runner/work/.../node_modules/vite/dist/node/chunks/dep-76613303.js:74639:28)
    at async doBuild (/home/runner/work/.../node_modules/vite/dist/node/chunks/dep-76613303.js:37652:20)
    at async build (/home/runner/work/.../node_modules/vite/dist/node/chunks/dep-76613303.js:37640:16)
    at async CAC.<anonymous> (/home/runner/work/.../node_modules/vite/dist/node/cli.js:738:9)
error Command failed with exit code 1.
```

**Comment by anncwb** [comment]
try 0.5.0

**Comment by wopian** [comment]
Updating to 0.5.1 after https://github.com/vbenjs/vite-plugin-compression/issues/13 was fixed works 👍
